### ISSUE TITLE
Panic when using Network printer that cannot be reached on the network

### ISSUE THREAD

**Issue by cmarquis** [local-group/rust-escposify#9]
When calling `Network::new()` if the configured IP address cannot be reached the thread panics.

It appears the source is simply calling `.unwrap()` on the tcp connection so it's not trapping any possible errors.

**Comment by stonewjr** [comment]
run copy testfile "\\\\LAPTOP-QV366NUQ\Receipt Printer" ok
but run examples\simple.rs no error and printer not things happened?
no error and no message ...

**Comment by stonewjr** [comment]
run in windows10
copy testfile "\\\\LAPTOP-QV366NUQ\Receipt Printer" ok
but run examples\simple.rs no error and printer not things happened?
no error and no message ...
